// const csv = require('csv-parser')
// const fs = require('fs')
// const results = [];

// fs.createReadStream('characterset2.csv')
//   .pipe(csv())
//   .on('data', (data) => results.push(data))
//   .on('end', () => {
//     console.log(results);
//     // [
//     //   { NAME: 'Daffy Duck', AGE: '24' },
//     //   { NAME: 'Bugs Bunny', AGE: '22' }
//     // ]
//   });

let encryptionTableArray = [
    { character: ' ', 'value': 'm' },
    { character: 'a', 'value': 'X' },
    { character: 'b', 'value': 'p' },
    { character: 'c', 'value': 'M' },
    { character: 'd', 'value': '*' },
    { character: 'e', 'value': 'D' },
    { character: 'f', 'value': '3' },
    { character: 'g', 'value': '£' },
    { character: 'h', 'value': '§' },
    { character: 'i', 'value': 't' },
    { character: 'j', 'value': 'Y' },
    { character: 'k', 'value': 'y' },
    { character: 'l', 'value': '7' },
    { character: 'm', 'value': '.' },
    { character: 'n', 'value': 'w' },
    { character: 'o', 'value': '!' },
    { character: 'p', 'value': '%' },
    { character: 'q', 'value': 'g' },
    { character: 'r', 'value': 'A' },
    { character: 's', 'value': 'u' },
    { character: 't', 'value': '2' },
    { character: 'u', 'value': 'J' },
    { character: 'v', 'value': '9' },
    { character: 'w', 'value': '_' },
    { character: 'x', 'value': '@' },
    { character: 'y', 'value': '[' },
    { character: 'z', 'value': 'L' },
    { character: 'A', 'value': 'h' },
    { character: 'B', 'value': 'q' },
    { character: 'C', 'value': '0' },
    { character: 'D', 'value': 'G' },
    { character: 'E', 'value': 'j' },
    { character: 'F', 'value': '^' },
    { character: 'G', 'value': 'Z' },
    { character: 'H', 'value': ']' },
    { character: 'I', 'value': 'I' },
    { character: 'J', 'value': '|' },
    { character: 'K', 'value': '>' },
    { character: 'L', 'value': 'B' },
    { character: 'M', 'value': 'c' },
    { character: 'N', 'value': 'i' },
    { character: 'O', 'value': 'e' },
    { character: 'P', 'value': ';' },
    { character: 'Q', 'value': '~' },
    { character: 'R', 'value': ':' },
    { character: 'S', 'value': 'P' },
    { character: 'T', 'value': '±' },
    { character: 'U', 'value': 'k' },
    { character: 'V', 'value': 'S' },
    { character: 'W', 'value': '&' },
    { character: 'X', 'value': '+' },
    { character: 'Y', 'value': 'l' },
    { character: 'Z', 'value': 'a' },
    { character: '!', 'value': ' ' },
    { character: '@', 'value': 'R' },
    { character: '£', 'value': ',' },
    { character: '$', 'value': '}' },
    { character: '%', 'value': 'n' },
    { character: '^', 'value': 'z' },
    { character: '&', 'value': 'F' },
    { character: '*', 'value': '8' },
    { character: '(', 'value': 'C' },
    { character: ')', 'value': '-' },
    { character: '-', 'value': '?' },
    { character: '_', 'value': 'x' },
    { character: '=', 'value': '5' },
    { character: '+', 'value': 'U' },
    { character: '[', 'value': 'K' },
    { character: ']', 'value': 'v' },
    { character: '{', 'value': '=' },
    { character: '}', 'value': '<' },
    { character: ';', 'value': '1' },
    { character: ':', 'value': 'd' },
    { character: "'", 'value': '{' },
    { character: `"`, 'value': 'N' },
    { character: '\\', 'value': 'O' },
    { character: `|`, 'value': 'b' },
    { character: `,`, 'value': '$' },
    { character: `.`, 'value': 'Q' },
    { character: `<`, 'value': 'H' },
    { character: `>`, 'value': '(' },
    { character: `/`, 'value': '\\' },
    { character: `?`, 'value': '4' },
    { character: `\``, 'value': ')' },
    { character: `~`, 'value': 's' },
    { character: `§`, 'value': '6' },
    { character: `±`, 'value': 'V' },
    { character: `1`, 'value': 'o' },
    { character: `2`, 'value': 'W' },
    { character: `3`, 'value': '"' },
    { character: '4', 'value': 'E' },
    { character: '5', 'value': "'" },
    { character: '6', 'value': 'r' },
    { character: '7', 'value': '/' },
    { character: '8', 'value': '`' },
    { character: '9', 'value': 'f' },
    { character: '0', 'value': 'T' }
]

